//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_AladinSclad.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventarizacia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventarizacia()
        {
            this.Invetarizacia_Tovar = new HashSet<Invetarizacia_Tovar>();
        }
    
        public int ID_Inventarizacii { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ID_Sotrudnika { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invetarizacia_Tovar> Invetarizacia_Tovar { get; set; }
    }
}
