//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_AladinSclad.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invetarizacia_Tovar
    {
        public int ID_Inventarizacii { get; set; }
        public int ID_Tovar { get; set; }
        public int Amount { get; set; }
    
        public virtual Inventarizacia Inventarizacia { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
