//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_AladinSclad.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSREntities1 : DbContext
    {
        public WSREntities1()
            : base("name=WSREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_tovarov> Category_tovarov { get; set; }
        public virtual DbSet<Dolzhnost> Dolzhnost { get; set; }
        public virtual DbSet<Inventarizacia> Inventarizacia { get; set; }
        public virtual DbSet<Invetarizacia_Tovar> Invetarizacia_Tovar { get; set; }
        public virtual DbSet<Postavki> Postavki { get; set; }
        public virtual DbSet<Postavki_Tovar> Postavki_Tovar { get; set; }
        public virtual DbSet<Postavshik> Postavshik { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
    }
}
