//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_AladinSclad.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Invetarizacia_Tovar = new HashSet<Invetarizacia_Tovar>();
            this.Postavki_Tovar = new HashSet<Postavki_Tovar>();
        }
    
        public int ID_Tovar { get; set; }
        public string Naimenovanie_tovara { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public Nullable<System.DateTime> Srok_godnosti { get; set; }
    
        public virtual Category_tovarov Category_tovarov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invetarizacia_Tovar> Invetarizacia_Tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavki_Tovar> Postavki_Tovar { get; set; }
    }
}
